# Matrix Tensors

In [2]:
import tensorflow as tf
import numpy as np
import torch

## Matrices in Numpy

In [4]:
X = np.array([[ 25, 2 ], [ 5, 26 ], [ 3, 7 ]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [5]:
# matrix dimensions
X.shape

(3, 2)

In [6]:
# area of matrix
X.size

6

In [8]:
# select left column
x[:,0]

array([25,  5,  3])

In [11]:
# select middle row
X[1,:]

array([ 5, 26])

In [15]:
# slicing matrix into 2x2 with indexing
x[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

## Matrices in PyTorch

In [16]:
X_pt = torch.tensor([[ 25, 2 ], [ 5, 26 ], [ 3, 7 ]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [17]:
X_pt.shape

torch.Size([3, 2])

In [20]:
# select middle row
X_pt[1,:]

tensor([ 5, 26])

## Matrices in TensorFlow

In [21]:
X_tf = tf.Variable([[ 25, 2 ], [ 5, 26 ], [ 3, 7 ]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [23]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [25]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [26]:
# select middle row
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>