# Norms & Unit Vectors

In [11]:
import numpy as np

In [12]:
x = np.array([ 25, 2, 5 ])
x

array([25,  2,  5])

## L<sup>2</sup> Norm
Describes the length or magnitude of a vector

In [13]:
# hard coded norm
(25**2 + 2**2 + 5**2)**0.5

25.573423705088842

In [14]:
# using numpy
np.linalg.norm(x)

25.573423705088842

## L<sup>1</sup> Norm
Describes the sum of the absolute values of the components of a vector

In [15]:
x

array([25,  2,  5])

In [16]:
# hard coded norm
np.abs(25) + np.abs(2) + np.abs(5)

32

## Squared L<sup>2</sup> Norm
Literally L<sup>2</sup> norm without the square root

In [17]:
# hard coded norm
(25**2 + 2**2 + 5**2)

654

In [18]:
# using numpy
np.dot(x, x)

654

## Max Norm
Describes the maximum of the absolute values of the components of a vector

In [19]:
x

array([25,  2,  5])

In [20]:
np.max(( np.abs(25), np.abs(2), np.abs(5) ))

25