# Vectors
* Individual components or elements of a vector are scalars
* Elements are accessed by index starting at 0

In [8]:
import tensorflow as tf
import pytorch as pt
import numpy as np

In [9]:
# showcase vector attributes
def vector_attrs(v):
    print(f"vector length:\t{ len(v) }")
    print(f"vector shape:\t{ v.shape }")
    print(f"vector type:\t{ type(v) }")
    print(f"vector x0:\t{ v[0] }") # python is 0 indexed

In [10]:
x = np.array([ 25, 2, 5 ]) # dtype=np.float16
x

array([25,  2,  5])

In [11]:
vector_attrs(x)

vector length:	3
vector shape:	(3,)
vector type:	<class 'numpy.ndarray'>
vector x0:	25


In [12]:
# cannot transpose 1D arrays through x.T, must use higher dimensions
y = np.array([[ 25, 2, 5 ]])
y

array([[25,  2,  5]])

In [13]:
vector_attrs(y)

vector length:	1
vector shape:	(1, 3)
vector type:	<class 'numpy.ndarray'>
vector x0:	[25  2  5]


In [14]:
# transpose row vector into a column vector
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [15]:
vector_attrs(y_t)

vector length:	3
vector shape:	(3, 1)
vector type:	<class 'numpy.ndarray'>
vector x0:	[25]


## Zero Vectors
* A vector with all elements equal to 0
* Can specify length & dimensions like ordinary vectors

In [17]:
z = np.zeros(3)
z

array([0., 0., 0.])